# RedstoneHelper v1.4
# Enable or disable the functions of the plugin
enabled: true
reverse:
  # Enable or disable ALL reversals.
  enabled: true
  #You can add your own types here.
  #Refer to https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for the correct block names
    types:
    - "PISTON"
    - "STICKY_PISTON"
    - "REPEATER"
    - "REDSTONE_WALL_TORCH"
    - "DROPPER"
    - "DISPENSER"
    - "COMPARATOR"
    - "OBSERVER"
fillables:
  #Enable or disable the fill function of this plugin
  enabled: true
  types:
    # Enable or disable the supported blocks
    # Do not add your own here, will not do anything.
    COMPOSTER:
      enabled: true
    END_PORTAL_FRAME:
      enabled: true
level:
  # Enable or disable fetching the level of a redstone wire
  enabled: true
  types:
    # Do not add your own here, will not do anything.
    REDSTONE_WIRE:
      enabled: true